volumes:
  mongo-data:
    external: true
services:
  mongo:
    image: mongo:6
    volumes:
      - ./setup/mongodb:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: travelsquared
      MONGO_INITDB_ROOT_PASSWORD: TS2022ddmbs
  mongo-express:
    build:
      context: setup/mongo-express
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: travelsquared
      ME_CONFIG_MONGODB_ADMINPASSWORD: TS2022ddmbs
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
  fastapi-traveltwo:
    build:
      context: ./fastapi-traveltwo
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-traveltwo:/app
    environment:
      DATABASE_URL: mongodb://travelsquared:TS2022ddmbs@mongo/admin
      WAIT_HOSTS: mongo:27017
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_FASTAPI_ACCOUNTS: http://localhost:8000
